sudo: required
services:
- docker

env:
  global:
  - IMAGE_NAME=otokarev/stellar-core

branches:
  only:
  - master
  - bare
  - /^v.*$/

script:
- docker build --pull --cache-from "$IMAGE_NAME" --tag "$IMAGE_NAME" .
before_script:
- if [ -z "$TRAVIS_TAG" ]; then exit 0; fi
- APP_VARIANT=${TRAVIS_TAG#*-} && [[ ${APP_VARIANT} = ${TRAVIS_TAG} ]] && APP_VARIANT="";
- APP_VERSION=${TRAVIS_TAG%-${APP_VARIANT}};
- APP_VERSION=${APP_VERSION} && [[ $APP_VERSION =~ ^v[0-9]+\.[0-9]+\.[0-9]+$ ]] || APP_VERSION=""
- [ -z "$APP_VERSION" ] && APP_VARIANT=""
#- APP_DOCKERFILE=Dockerfile && [[ -n $APP_VARIANT ]] && APP_DOCKERFILE="Dockerfile.${APP_VARIANT}"
#- [ -n "$APP_VERSION" ] && sed -i 's/^ENV\s*STELLAR_CORE_VERSION.*$/ENV STELLAR_CORE_VERSION='$APP_VERSION'/' $APP_DOCKERFILE
#- docker pull "$IMAGE_NAME" || true
#
#script:
#- docker build --pull --cache-from "$IMAGE_NAME" --tag "$IMAGE_NAME" .
#
#after_script:
#- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
#- docker tag "$IMAGE_NAME" "${IMAGE_NAME}:${TRAVIS_TAG}" && docker push "${IMAGE_NAME}:${TRAVIS_TAG}"
# - [ -n $APP_VARIANT ] && docker tag "$IMAGE_NAME" "${IMAGE_NAME}:${APP_VARIANT}" && docker push "${IMAGE_NAME}:${APP_VARIANT}"
# - [ -n $APP_VERSION ] && docker tag "$IMAGE_NAME" "${IMAGE_NAME}:latest" && docker push "${IMAGE_NAME}:latest"
